### ISSUE TITLE
Possible to include delay or timeout?  SPA not rendered before captured.

### ISSUE THREAD

**Issue by RossRogers** [en-japan-air/prerender-chrome-headless#2]
Your stock application doesn't work for my [react-static-boilerplate](https://github.com/kriasoft/react-static-boilerplate) based SPA.  React hasn't rendered the page when `loadEventFired()` has returned.  If I add a delay in your `index.js`, then react has time to render inside of chrome:

      () => debug('Waiting for page load event to be fired'),
      () => Page.loadEventFired(),
      () => { var r; let p= new Promise((resolve,reject) => r = resolve); setTimeout(()=> r(),3000); return p },

Is there an event that specifies that the SPA has rendered or can you add a delay option for the user?

**Comment by piuccio** [comment]
thanks for trying out this project. Sure it sounds like a reasonable option.

**Comment by RossRogers** [comment]
The `setTimeout` seems silly, but I'm not sure what other events are available.

**Comment by piuccio** [comment]
I made a PR for adding a timeout. Feel free to comment it

**Comment by RossRogers** [comment]
Looks good to me :-)

**Comment by piuccio** [comment]
Published in `1.1.0`
